language: php

sudo: false

compiler:
  - gcc
  - clang

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

cache:
    - apt

env:
  # gcc x
  - CC="gcc" DB="mysql"
  - CC="gcc" DB="pgsql"
  # clang x
  - CC="clang" DB="mysql"
  - CC="clang" DB="pgsql"

services:
  - memcached
  - redis-server

install:
  - composer self-update
  - composer --prefer-source install
  - apt-get update
  - sh tests/ci/$DB.sh

before_script:
  - phpenv config-add tests/ci/drivers.ini
  - git submodule --quiet update --init --recursive

script:
  - (cd vendor/phalcon/zephir; ./unit-tests/ci/before_install.sh; ./install)
  - (./tests/ci/install_zephir.sh)
  - ./vendor/bin/zephir generate
  - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall"; phpize && ./configure --enable-owl && make --silent -j4 && sudo make --silent install && phpenv config-add ../tests/ci/owl.ini)
  - ulimit -c unlimited || true
  - (cd examples/rest-app; composer install; php public/index.php)
  - (cd examples/mvc-app; composer install; php public/index.php)
  - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 --ignore=autoload_real.php unit-tests/ examples/
  - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes --leak-check=full phpunit -v --debug --configuration tests/travis/$DB.travis.xml

after_failure:
  - sudo apt-get -qq install gdb
  - ./tests/ci/after_failure.sh

addons:
  apt:
    packages:
      - gdb
      - valgrind
      - re2c
